COMP = hipcc

CXXFLAGS = -O3 -fopenmp

CPPFLAGS = -I${MPICH_DIR}/include

LDFLAGS = -L${MPICH_DIR}/lib -L${CRAY_MPICH_ROOTDIR}/gtl/lib
LIBS = -lmpi -lmpi_gtl_hsa

hello_jobstep_hip.x: hello_jobstep_hip.o
	${COMP} ${LDFLAGS} ${LIBS} ${CXXFLAGS} hello_jobstep_hip.o -o hello_jobstep_hip.x

hello_jobstep_hip.o: hello_jobstep_hip.cpp
	${COMP} ${CPPFLAGS} ${CXXFLAGS} -c hello_jobstep_hip.cpp

